# Generated by Django 5.0.14 on 2025-04-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'RoleMaster',
            },
        ),
        migrations.CreateModel(
            name='usermaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('pwd', models.CharField(max_length=100)),
                ('roleid', models.IntegerField()),
                ('working_status', models.IntegerField()),
                ('logged_in_status', models.IntegerField()),
            ],
            options={
                'db_table': 'usermaster',
            },
        ),
    ]
