# Generated by Django 5.0.14 on 2025-04-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_partner_name', models.CharField(max_length=200)),
                ('login_creation_date', models.DateField()),
                ('login_validity_date', models.DateField()),
                ('GLN', models.CharField(max_length=13)),
                ('company_prefix', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('spoc_first_name', models.CharField(max_length=50)),
                ('spoc_last_name', models.CharField(max_length=50)),
                ('spoc_phone', models.CharField(max_length=20)),
                ('spoc_work_phone', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('gps_coordinates', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('logged_in_status', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
