# Generated by Django 5.0.14 on 2025-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('role_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'UserRoleMapping',
            },
        ),
    ]
