# Generated by Django 5.0.14 on 2025-04-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_userrolemapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrolemapping',
            old_name='uname',
            new_name='username',
        ),
    ]
