# Generated by Django 5.0.14 on 2025-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0003_rename_uname_userrolemapping_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSCCBarcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('extension_digit', models.CharField(max_length=1)),
                ('company_prefix', models.CharField(max_length=12)),
                ('serial_reference', models.CharField(max_length=12)),
                ('check_digit', models.CharField(max_length=1)),
                ('full_sscc', models.CharField(max_length=18, unique=True)),
                ('barcode_image', models.ImageField(upload_to='sscc_barcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SSCCBarcode',
            },
        ),
    ]
