# Generated by Django 5.0.14 on 2025-05-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0004_ssccbarcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGTINBarcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gtin', models.CharField(max_length=14)),
                ('expiry', models.CharField(max_length=6)),
                ('serial', models.CharField(max_length=50)),
                ('barcode_image', models.ImageField(upload_to='sgtin_barcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SGTINBarcode',
            },
        ),
    ]
