# Generated by Django 5.0.14 on 2025-05-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0005_sgtinbarcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgtinbarcode',
            name='barcode_image',
            field=models.ImageField(max_length=500, upload_to='sgtin_barcodes/'),
        ),
        migrations.AlterField(
            model_name='sgtinbarcode',
            name='serial',
            field=models.CharField(max_length=100),
        ),
    ]
