# Generated by Django 5.0.14 on 2025-05-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0006_alter_sgtinbarcode_barcode_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgtinbarcode',
            name='barcode_image',
            field=models.ImageField(upload_to='sgtin_barcodes/'),
        ),
        migrations.AlterField(
            model_name='sgtinbarcode',
            name='gtin',
            field=models.CharField(max_length=18),
        ),
    ]
