# Generated by Django 5.0.14 on 2025-05-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0007_alter_sgtinbarcode_barcode_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgtinbarcode',
            name='expiry',
            field=models.CharField(max_length=10),
        ),
    ]
