# Generated by Django 5.0.14 on 2025-06-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0008_alter_sgtinbarcode_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('account_alias', models.CharField(max_length=50)),
                ('GLN', models.CharField(max_length=13)),
                ('company_prefix', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('ContactNo', models.CharField(max_length=20)),
                ('LocationName', models.CharField(max_length=50)),
                ('LocationType', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('gps_coordinates', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'CompanyDetails',
            },
        ),
    ]
