# Generated by Django 5.0.14 on 2025-06-30 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0009_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='business_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='sub_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
