# Generated by Django 5.0.14 on 2025-06-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0010_companydetails_business_type_companydetails_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='GLN',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='company_prefix',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='gps_coordinates',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='spoc_first_name',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='spoc_last_name',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='spoc_phone',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='spoc_work_phone',
        ),
    ]
